package com.runningmessage.weather.domain

import com.runningmessage.weather.db.ForecastDb
import com.runningmessage.weather.domain.model.Forecast
import com.runningmessage.weather.domain.model.ForecastList
import com.runningmessage.weather.net.ForecastRequest

/**
 * Created by Lorss on 18-12-17.
 */
class ForecastServer(private val dataMapper: ServerDataMapper = ServerDataMapper()
                     , private val forecastDb: ForecastDb = ForecastDb()) : ForecastDataSource {

    override fun requestDayForecast(id: Long): Forecast? = throw    UnsupportedOperationException()

    override fun requestForecastByZipCode(zipCode: Long, date: Long): ForecastList? {

        val result = ForecastRequest(zipCode.toString()).execute()

        val converted = dataMapper.convertFromDataModel(result)


        forecastDb.saveForecast(converted)

        //because we need to use the id generated by database
        return forecastDb.requestForecastByZipCode(zipCode, date)

    }

}